# Generated by Django 4.1.1 on 2022-11-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="handbags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disc", models.TextField()),
                ("price", models.TextField()),
                ("image", models.TextField()),
                ("image1", models.TextField()),
                ("cat", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="kids",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disc", models.TextField()),
                ("price", models.TextField()),
                ("image", models.TextField()),
                ("image1", models.TextField()),
                ("cat", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="men",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disc", models.TextField()),
                ("price", models.TextField()),
                ("image", models.TextField()),
                ("image1", models.TextField()),
                ("cat", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="women",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disc", models.TextField()),
                ("price", models.TextField()),
                ("image", models.TextField()),
                ("image1", models.TextField()),
                ("cat", models.TextField()),
            ],
        ),
    ]
